### ISSUE TITLE
insertAdjacentHTML _slight_ performance improvement

### ISSUE THREAD

**Issue by rijkvanzanten** [Murderlon/web-app-from-scratch#10]
[The insertion of HTML into the dom](https://github.com/Murderlon/web-app-from-scratch/blob/master/src/Week-2/static/js/main.js#L33) could be optimized even more. Instead of calling `insertAdjacentHTML` for each array item, try reducing all elements into one string. That way, you only have to call `insertAdjacentHTML` once

**Comment by Murderlon** [comment]
Done!
