### ISSUE TITLE
This.

### ISSUE THREAD

**Issue by rijkvanzanten** [Murderlon/web-app-from-scratch#11]
I judge. 

[https://github.com/Murderlon/web-app-from-scratch/blob/master/src/Week-2/static/js/main.js#L42](https://github.com/Murderlon/web-app-from-scratch/blob/master/src/Week-2/static/js/main.js#L42)

**Comment by nickrttn** [comment]
It's not PE to hide by default. You could look up FLIP animations. I know the DOM can be a bitch to deal with when you want to animate on pageload, but it can be done 👍

**Comment by nickrttn** [comment]
https://aerotwist.com/blog/flip-your-animations/

**Comment by Murderlon** [comment]
✅
