### ISSUE TITLE
Don't use setTimeout when you don't need to (not judging ;-)

### ISSUE THREAD

**Issue by joostf** [Murderlon/web-app-from-scratch#17]
https://github.com/Murderlon/web-app-from-scratch/blob/5ea47b3097df5d07d78f08fad4de84e8841418da/src/Week-2/static/js/main.js#L46

set translateY to 650px instead of -150px
and add animation-fill-mode: forwards; to preserve value of last key frame!
https://github.com/Murderlon/web-app-from-scratch/blob/5ea47b3097df5d07d78f08fad4de84e8841418da/src/Week-2/static/css/style.css#L64

May with you be the force, young Merlin!

**Comment by Murderlon** [comment]
Done!
