### ISSUE TITLE
Use of constants

### ISSUE THREAD

**Issue by BerendPronk** [Murderlon/web-app-from-scratch#3]
It's a common coding conventions to write constants down in all-uppercase characters. This also makes it possible to immediately identify a constant when you're working in a large JavaScript file.

`const APP;` instead of `const app;`

**Comment by Murderlon** [comment]
In my opinion that only works for single word `const`'s, like `APP`. But `allSections` would become `ALL_SECTIONS`, and I definitely prefer camelCase over under_score.
