### ISSUE TITLE
Why split out this functionality?

### ISSUE THREAD

**Issue by nickrttn** [Murderlon/web-app-from-scratch#7]
Why split out the functionality in this file? Can't you handle this in an init somewhere in your application?

https://github.com/Murderlon/web-app-from-scratch/blob/master/src/Week-2/static/js/hide.js

**Comment by nickrttn** [comment]
For instance, include it in https://github.com/Murderlon/web-app-from-scratch/blob/master/src/Week-2/static/js/main.js#L26

**Comment by Murderlon** [comment]
Done!
