### ISSUE TITLE
Abstraction level

### ISSUE THREAD

**Issue by nickrttn** [Murderlon/web-app-from-scratch#8]
Even though abstraaction is often necessary and great, I think you try to do too much too often. Your app could be more readable by *decreasing* the abstraction level. For instance, the https://github.com/Murderlon/web-app-from-scratch/blob/master/src/Week-2/static/js/main.js#L42 `update()` function here could be split up into three named functions that clearly state what they update.

**Comment by nickrttn** [comment]
Also, something like a model is an abstract concept. Usually a model describes a specific set of data, like a User. You're trying to abstract your models into an overarching function that generates data, kind of like a factory. While not necessarily horribly and absolutely a matter of taste, abstracting like this too early often leads to errors that are hard to explain later on. I would advise to separate out your models and DOM operations to be able to support your different datamodels (Planet, Person, Starship).

**Comment by Murderlon** [comment]
Split update into multiple functions depening on the state - Done!

**Comment by Murderlon** [comment]
How would you approach the model though?
Should I introduce a fourth object called `init` with parameters that define sequence of events, and keep `model` just for fetching and adapting data?

**Comment by nickrttn** [comment]
You could write a `model.fetch()` function that fetches data, which is called from each of the separate models. You could init the models from an `model.init()` function, or call them all separately from outside of their defining class. 

I wouldn't define a sequence as such, just asynchronously call the data fetching methods of each of your models. and have them handle their own data as it comes back. You create a little more DOM operations this way, so at a larger scale it might perform a little less, but it won't be an issue for now, and it will make your code easier to reason about.
